### ISSUE TITLE
Add personas

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/ecosystem#23]
As the summary says. Later, we can then group stories by personas

**Comment by raphaelfournier** [comment]
Personas are close to stories (stored as <story-name>/readme/md files). 
Work needed:
- find how to render the readme.md file into html, along with the <story-name>.md
- provide access (dedicated page) to the list of personas (probably not with a _data/personas.yml, because of spaces in names, a loop over stories should be enough)
